// <auto-generated />
namespace TreaviceAlpha.Migrations.UserProfileContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddProfileAwarenessToTroveRemoveFromTreasure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProfileAwarenessToTroveRemoveFromTreasure));
        
        string IMigrationMetadata.Id
        {
            get { return "201706122118358_AddProfileAwarenessToTroveRemoveFromTreasure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
